Lesson_6/Transport file added
Hlieb/HomeworkFromNikita pull request #1
Opened 2021-09-14 17:56 UTC by Hlieb

28

2021-09-15 02:20 UTC, nickrogracher requested changes
Сделай правки, коммить/пуш изменения, ответь что-нибудь в комментах (на повторяющиеся проблемы не нужно) + нажми на `resolve conversation`, НЕ СОЗДАВАЙ новый ПР, а просто кидай мне ссылку на этот

2021-09-15 02:20 UTC, nickrograch commented on src/java/Transport.java
> +    }
@Hlieb Читай внимательно задание
![image](https://user-images.githubusercontent.com/48067169/133353568-dd212181-97e9-4c78-a80c-707a0f4db466.png)

2021-09-15 02:20 UTC, nickrograch commented on src/java/Transport.java
> +    }
@Hlieb 
![image](https://user-images.githubusercontent.com/48067169/133353687-00124201-6dfb-4a46-9e52-f343e2a1d665.png)
Это значит, что сам расчет отдельно ничего не выводит на экран.
Переделай метод так, чтобы он присваивал расчитанное значение переменной _power_ для конкретного экземпляра класса

2021-09-15 02:20 UTC, nickrograch commented on src/java/Air_transport.java
> + public  abstract class Air_transport extends Transport {
@Hlieb 
Поменяй название класса на CamelCase подобное

2021-09-15 02:20 UTC, nickrograch commented on src/java/Transport.java
> +    }
Это значит, что реализация не нужна. тебе нужно сделать этот метод методом без реализации

2021-09-15 02:20 UTC, nickrograch commented on src/java/Transport.java
> +    void Vyvod(){                                       //Метод вывода параментров
@Hlieb Поменяй название метода на английское слово

2021-09-15 02:20 UTC, nickrograch commented on src/java/Air_transport.java
> +    }
@Hlieb Еще раз подумай исходя из задания, нужна ли тут реализация этого метода

2021-09-15 02:20 UTC, nickrograch commented on src/java/Air_transport.java
> +    void Vyvod() {
@Hlieb название метода

2021-09-15 02:20 UTC, nickrograch commented on src/java/Land_transport.java
> +public abstract class Land_transport extends Transport {
@Hlieb поменяй на CamelCase название `Land_transport`

2021-09-15 02:20 UTC, nickrograch commented on src/java/Land_transport.java
> +    }
@Hlieb И снова подумай о необходимости реализации и заодно название метода `Vyvod()` на английский

2021-09-15 02:20 UTC, nickrograch commented on src/java/Civil.java
> +public class Civil extends Air_transport {
@Hlieb Название класса `Civil` поменять на `ГражданскийВоздушныйТранспорт`(на англиском)

2021-09-15 02:20 UTC, nickrograch commented on src/java/Civil.java
> +    void Vyvod() {
@Hlieb `Vyvod()` имя метода

2021-09-15 02:20 UTC, nickrograch commented on src/java/Civil.java
> +    }
@Hlieb 
![image](https://user-images.githubusercontent.com/48067169/133354718-a42b32e2-c5fc-4e0b-9b2b-0e2163665f15.png)
А у тебя этот метод ничего не возвращает, следовательно сделай его не `void`, а `String` 
Плюс у тебя должно быть еще 1 поле у класса - `descriptionString`, которое будет хранить эту строку с описанием

2021-09-15 02:20 UTC, nickrograch commented on src/java/Civil.java
> +        Scanner scanner=new Scanner(System.in);
@Hlieb Между операторами всегда ставь пробелы для лучшей читаемости кода!
```suggestion
        Scanner scanner = new Scanner(System.in);
```

2021-09-15 02:20 UTC, nickrograch commented on src/java/Civil.java
> +    int NumberOfPassengers;
@Hlieb названия переменных всегда начинается с маленькой буквы, применяется шаблон _camelCase_
Плюс эта переменная хранит значение максимального количество пасажиров, так и назови `максЦифраПасажиров`(на англ)

2021-09-15 02:20 UTC, nickrograch commented on src/java/Civil.java
> +        if(NumberOfPassengers>=passangers) {
@Hlieb снова пробелы между операторами
```suggestion
        if(NumberOfPassengers >= passangers) {
```

2021-09-15 02:20 UTC, nickrograch commented on src/java/Civil.java
> +        }
@Hlieb  Внимательно читай условие
![image](https://user-images.githubusercontent.com/48067169/133355666-f477e025-93f1-4daa-9c1d-0ecf892ec8e0.png)
следовательно, должно выводиться 

> _Самолёт заполнен_    
 **Можно на англ**

> _Вам нужен самолёт побольше_ 
 **Тут на англ верно**

2021-09-15 02:20 UTC, nickrograch commented on src/java/Freight_transport.java
> +public class Freight_transport extends Land_transport{
@Hlieb Название кдасса - CamelCase + должно быть `ГрузовойНаземныйТранспорт`(на англ)

2021-09-15 02:20 UTC, nickrograch commented on src/java/Freight_transport.java
> +    }
@Hlieb 
![image](https://user-images.githubusercontent.com/48067169/133355938-01da2a58-adad-46ee-9a5d-d50c7bb4da4e.png)

Опять таки читаем внимательно, что требуют

2021-09-15 02:20 UTC, nickrograch commented on src/java/Freight_transport.java
> +        Scanner scanner=new Scanner(System.in);
@Hlieb пробелы и операторы
```suggestion
        Scanner scanner = new Scanner(System.in);
```

2021-09-15 02:20 UTC, nickrograch commented on src/java/Freight_transport.java
> +    double CarryingCapacity;
@Hlieb camelCase

2021-09-15 02:20 UTC, nickrograch commented on src/java/Freight_transport.java
> +        int CargoWeight = scanner.nextInt();
`CargoWeight`  -- исправь, camelCase

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +public class Light_vehicle extends Land_transport{
@Hlieb Имя класса  -  CamelCase + `ЛегковойНаземныйТранспорт`

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +    int NumberOfSeats;
@Hlieb имена переменных исправь, camelCase

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +    private double a;
@Hlieb что это за переменная  
`private double a;`? измени название, чтобы было понятно зачем она
```suggestion
    private double fuelConsumedAmount;
```

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +    }
@Hlieb Название + смотрим условие задачи и меняем

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +    void Dvizhenije(){
@Hlieb Никаких транслитов в названиях

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +    private int travel;
@Hlieb ааа переменная `travel` - пройденный маршрут! Так и назови переменную: `пройденныйМаршрут`

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +        travel=time*maksSpeed;
@Hlieb Операторы и пробулы
```suggestion
        time = scanner.nextInt();
        travel = time * maksSpeed;
```

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +    }
@Hlieb Переделай метод `private void rashod()` так, чтобы он возвращал double значение. Т.е.
```suggestion
   private String rashod(){
         fuelConsumedAmount = travel / FuelConsumption;
         return fuelConsumedAmount 
   }      
```
или еще проще:
```suggestion
    private String rashod(){
        return (travel / FuelConsumption);
    }
```

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +         a =travel/FuelConsumption;
@Hlieb Операторы и пробелы
```suggestion
         a = trave l/ FuelConsumption;
```

2021-09-15 02:20 UTC, nickrograch commented on src/java/Light_vehicle.java
> +    }
@Hlieb операторы и пробелы + убрать лишнюю конкатенацию строк.
```suggestion
        System.out.println("During the time " + time + " h, the car " + carModel + " moving with the maximum speed " + maksSpeed + " km/h " + "will ride " + travel + " km and consume " + a + " liters of fuel" );
    }
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Military.java
> +public class Military extends Air_transport {
@Hlieb Имя класса - `ВоенныйВоздушныйТранспорт`

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Military.java
> +    int NumberOfMissiles;
@Hlieb имена переменных - camelCase

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Military.java
> +    }
@Hlieb читаем условие и реализовываем метод `Vyvod()` верно + помним про запрет на транслитерацию

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Military.java
> +            System.out.println("Bailout Successful");}
@Hlieb Чутка не красиво так
```suggestion
            System.out.println("Bailout Successful");
      }
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Main.java
> +        Scania.loading();
1.  пробелы и операторы
```suggestion
        Civil AN = new Civil();
        AN.BusinessClass = false;
        AN.NumberOfPassengers = 20;
        AN.maksSpeed = 700;
               ............
```
2. Для всех классов создать конструктор (если не помнишь, загугли) чтобы создавать объекты не таким некрасивым способом
   ```suggestion
        Civil AN = new Civil(false, 20, 700, 250, 1000, 50);
        AN.Vyvod();
        AN.Power();
        AN.loading();
        Military MIG = new Military(600, 200, 1500, true, 10);
        MIG.Vyvod();
        MIG.Power();
        MIG.ejection();
        MIG.shot();
        Light_vehicle BMW = new Light_vehicle(4, 13000, 250, 4, "BMW", 550, 20);
        BMW.Vyvod();
        BMW.Power();
        BMW.Dvizhenije();
        .............................
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Main.java
> +        BMW.carModel=new String("BMW");
@Hlieb Не нужно создавать новый объект типа `String` можно просто
```suggestion
        BMW.carModel = "BMW";
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Main.java
> +        Scania.carModel=new String("Scania");
@Hlieb Не нужно создавать новый объект типа String можно просто
```suggestion
        Scania.carModel = "Scania";
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Main.java
> +        Civil AN=new Civil();
@Hlieb имена объектов/экземпляров класса всегда с маленькой буквы
```suggestion
        Civil aN=new Civil();
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Main.java
> +        Military MIG= new Military();
@Hlieb имена объектов/экземпляров класса всегда с маленькой буквы
```suggestion
        Military mIG= new Military();
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Main.java
> +        Light_vehicle BMW=new Light_vehicle();
@Hlieb имена объектов/экземпляров класса всегда с маленькой буквы
```suggestion
        Light_vehicle bMW=new Light_vehicle();
```

2021-09-15 02:20 UTC, nickrogracher commented on src/java/Main.java
> +        Freight_transport Scania=new Freight_transport();
@Hlieb имена объектов/экземпляров класса всегда с маленькой буквы
```suggestion
        Freight_transport scania=new Freight_transport();
```

2021-09-15 17:37 UTC, Hlieb commented on src/java/Air_transport.java
> + public  abstract class Air_transport extends Transport {
исправил

2021-09-28 17:43 UTC, nickrogracher commented on src/java/CivilAirTransport.java
> +        this.businessClass=businessClass;
@Hlieb Старайся ставить пробелы между операторами
```suggestion
        this.maksNumberOfPassengers = maksNumberOfPassengers;
        this.businessClass = businessClass;
```

2021-09-28 17:44 UTC, nickrograch commented on src/java/FreightLandTransport.java
> +
@Hlieb Ненужные пустые строки

2021-09-28 17:44 UTC, nickrogracher commented on src/java/LandTransport.java
> +
@Hlieb Пустая строка)

2021-09-28 17:45 UTC, nickrogracher commented on src/java/LightVehicle.java
> +
@Hlieb  И снова пуустая)

2021-09-28 17:48 UTC, nickrogracher approved these changes
Мелкие, косметические недочеты, но в целом здорово)

2021-09-28 17:48 UTC, nickrogracher commented on src/java/MilitaryAirTransport.java
> +    void shot() {
@Hlieb А вот между методами лучше оставлять 1 пустую строку
```suggestion
    }
    
    void shot() {
```

2021-09-28 17:48 UTC, nickrogracher commented on src/java/MilitaryAirTransport.java
> +    void ejection(){
@Hlieb То же самое
```suggestion
    }
    
    void ejection(){
```

2021-09-28 17:48 UTC, nickrogracher commented on src/java/Transport.java
> +        this.carModel=carModel;
@Hlieb Старайся отделять пробелами операторы
```suggestion
        this.maksSpeed = maksSpeed;
        this.weight = weight;
        this.carModel = carModel;
```

2021-09-28 17:48 UTC, nickrogracher commented on src/java/Transport.java
> +
@Hlieb Лишняя пустая строка

2021-09-28 17:49 UTC, merged